name: FairPriceKe CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-scraping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
      working-directory: ./web-scraping
    - name: Run tests
      run: npm test
      working-directory: ./web-scraping

  # backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #     working-directory: ./backend
  #   - name: Run tests
  #     run: python -m unittest discover tests
  #     working-directory: ./backend
  #
  # frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #   - name: Install dependencies
  #     run: npm ci
  #     working-directory: ./frontend
  #   - name: Run tests
  #     run: npm test
  #     working-directory: ./frontend
  #
  # data-analysis:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #     working-directory: ./data-analysis
  #   - name: Run notebooks
  #     run: |
  #       pip install jupyter
  #       jupyter nbconvert --to notebook --execute notebooks/*.ipynb
  #     working-directory: ./data-analysis
  #
  # ml:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #     working-directory: ./ml
  #   - name: Run tests
  #     run: python -m unittest discover tests
  #     working-directory: ./ml
