name: Web Scraping CI

on:
  push:
    paths:
      - 'web-scraping/**'
  pull_request:
    paths:
      - 'web-scraping/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Web Scraping CI
        run: |
          cd web-scraping
